version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-ppassword",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mynetwork
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  user-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_URL=user:password@tcp(mysql:3306)/testdb?parseTime=true
    networks:
      - mynetwork
    volumes:
      - ./database/migrations:/app/database/migrations


networks:
  mynetwork:



  # user-service:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_PORT: 3306
  #     MYSQL_DATABASE: testdb
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password

  #   networks:
  #     - mynetwork
  #   volumes:
  #     - ./database/migrations:/migrations

