name: CI Pipeline

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: testdb
        run: go test ./...

      - name: Build the application
        run: go build -v ./...

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        run: |
          echo "Deploying application..."
          # Add your deployment commands here (e.g., SSH to server and deploy)


# name: CI

# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     services:
#       mysql:
#         image: mysql:8.0
#         env:
#           MYSQL_ROOT_PASSWORD: password
#           MYSQL_DATABASE: testdb
#           MYSQL_USER: user
#           MYSQL_PASSWORD: password
#         ports:
#           - 3306:3306
#         options: >-
#           --health-cmd "mysqladmin ping -user -password"
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Go
#       uses: actions/setup-go@v2
#       with:
#         go-version: 1.20

#     - name: Install dependencies
#       run: go mod download

#     - name: Wait for MySQL to be healthy
#       run: |
#         for i in `seq 1 30`; do
#           nc -z localhost 3306 && echo Success && exit 0
#           echo -n .
#           sleep 1
#         done
#         echo Failed waiting for MySQL && exit 1

#     - name: Run migrations and tests
#       env:
#         DATABASE_URL: "user:password@tcp(localhost:3306)/testdb?parseTime=true"
#       run: go run main.go &
#           go test -v ./...
