name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -user -password"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Install dependencies
      run: go mod download

    - name: Wait for MySQL to be healthy
      run: |
        for i in `seq 1 30`; do
          nc -z localhost 3306 && echo Success && exit 0
          echo -n .
          sleep 1
        done
        echo Failed waiting for MySQL && exit 1

    - name: Run migrations and tests
      env:
        DATABASE_URL: "user:password@tcp(localhost:3306)/testdb?parseTime=true"
      run: go run main.go &
          go test -v ./...

# name: Ci

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   audit:
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up Go
#         uses: actions/setup-go@v2
#         with:
#           go-version: 1.17

#       - name: Verify dependencies
#         run: go mod verify

#       - name: Build
#         run: go build -v ./...

#       - name: Run go vet
#         run: go vet ./...

#       - name: Install staticcheck
#         run: go install honnef.co/go/tools/cmd/staticcheck@latest

#       - name: Run staticcheck
#         run: staticcheck ./...

#       - name: Install golint
#         run: go install golang.org/x/lint/golint@latest

#       - name: Run golint
#         run: golint ./...

#       - name: Run tests
#         run: go test -race -vet=off ./...
